// Generated by CoffeeScript 1.3.3
var d, dat, i, svgscale;



 d3.csv("Test.csv", function(dat) {
     console.log(dat[0]);

     for (i in dat) {
  d = dat[i];
  d.x = +d.Year;
  d.y = +d.RX_Speed;
}
   
svgscale = plotframe(dat, {
  chartname: "#plotframe",
  xlab: "Year",
  ylab: "RX_Speed",
  pad: {
    bottom: 50,
    left: 50,
    top: 3,
    right: 3,
    scale: 0.05
  },
  tickPadding: 6,
  ylab_rotate: 270
});
console.log("Line 64")

svgscale.svg.selectAll("circle", {
  chartname: "#plotframe"
}).data(dat).enter().append("circle").attr("cx", function(d) {
  console.log(d);
  return svgscale.x(d.x);
}).attr("cy", function(d) {
  console.log(d);
  return svgscale.y(d.y);
}).attr("r", 5).attr("fill", "slateblue").on("mouseover", function() {
  return d3.select(this).transition().attr("fill", "hotpink");
}).on("mouseover.tooltip", function(d, i) {
  return svgscale.svg.append("text").text(d.Authors+ " " +d.Affiliates).attr("id", "tooltip").attr("x", svgscale.x(d.x) + 10).attr("y", svgscale.y(d.y)).attr("fill", "hotpink").attr("opacity", 0).style("font-family", "sans-serif").transition().attr("opacity", 1);
}).on("mouseout", function() {
  d3.select(this).transition().duration(500).attr("fill", "slateblue");
  return d3.selectAll("#tooltip").transition().duration(500).attr("opacity", 0).remove();
});
});